### ISSUE TITLE
Normalize identifiers

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Tests#41]
There are many test assets that use PUBCHEM.COMPOUND ids.   With the latest updates to biolink and nodenorm, these will probably need to change to CHEBIs.  For instance TestAsset 305 has a chemical of PUBCHEM.COMPOUND:2973 and it will soon be updated to a CHEBI.

If the testrunner handles normalization then this will not need to be done, or not done at the testasset level anyway.

**Comment by sandrine-muller-research** [comment]
To answer your question, I report what the UI tells me even if the ID is not the preferred one. If there is an issue with the normalization itself (e.g. 2 results with the same compound but different ID for instance), I create an additional issue in the feedback repo.

Generally speaking, I was wondering how will we be handling normalization tests/issues in general? It happened to me that the reported ID was not the correct one (wrong ID) and I put them in a separate suite for the moment.

**Comment by gaurav** [comment]
My current plan is to upgrade NodeNorm CI this Thursday (May 2) so that it will have those updated IDs after then, but if you'd like more time to update the test runner, let me know and I can delay that upgrade to next week! NodeNorm Test and Prod will remain unchanged until everybody is happy with NodeNorm CI.

**Comment by maximusunc** [comment]
Normalization has been added to the Test Harness, so we should be evaluating against all primary identifiers from node norm.
